### ISSUE TITLE
No Active - No Connected

### ISSUE THREAD

**Issue by Ajwah** [nicollasricas/vscode-streamdeck#10]
I previously submitted an issue similar to this [here](https://github.com/nicollasricas/vscode-streamdeck/issues/7)

This time, when starting up Visual Studio Code, it states: `Deck | Connecting` but unlike before it does not change to `Deck | Connected`
<img width="209" alt="Screen Shot 2020-06-08 at 1 51 10 AM" src="https://user-images.githubusercontent.com/11848116/83996594-89922b80-a92a-11ea-8b18-6a9dc0f3005c.png">

The main issue this time based on the Debug Output I shared below is that the websocket is not open:
> [ERROR] WebSocket is not open: readyState 0 (CONNECTING), Stack: Error: WebSocket is not open: readyState 0 (CONNECTING)

Below I am sharing all what I have:

> Wich OS are you using? 

macOS

> What plugin version are you using (stream deck side)?

`5.1.2`
<img width="837" alt="Screen Shot 2020-06-08 at 1 53 34 AM" src="https://user-images.githubusercontent.com/11848116/83996772-dfff6a00-a92a-11ea-96df-725f6f214b84.png">

> What extension version you have installed? (vscode side)?

`4.1.5`
<img width="1394" alt="Screen Shot 2020-06-08 at 1 49 42 AM" src="https://user-images.githubusercontent.com/11848116/83996499-5354ac00-a92a-11ea-864e-94d8efba0b1c.png">

> What are extension settings? (vscode side)?

<img width="1363" alt="Screen Shot 2020-06-08 at 1 57 09 AM" src="https://user-images.githubusercontent.com/11848116/83996985-60be6600-a92b-11ea-8824-34174ea4cb54.png">

> What are extension settings? (settings.ini side)?

![Screen Shot 2020-06-08 at 1 56 11 AM](https://user-images.githubusercontent.com/11848116/83996921-3c628980-a92b-11ea-83ef-3dbb2a3e0717.png)
Kindly take note that [like previously](https://github.com/nicollasricas/vscode-streamdeck/issues/7#issuecomment-623766900), I had to recreate it as you explained [here](https://github.com/nicollasricas/vscode-streamdeck/issues/7#issuecomment-632760075)

> Debug Output

```
[6/8/2020, 1:42:40 AM] Connecting to Stream Deck
[6/8/2020, 1:42:40 AM] Registering session e5564f1a-003f-41bf-be74-0b4ee7a72b871591594958666
[6/8/2020, 1:42:44 AM] Disconnected from Stream Deck.
[6/8/2020, 1:42:44 AM] Connecting to Stream Deck
[6/8/2020, 1:46:00 AM] Activation requested to e5564f1a-003f-41bf-be74-0b4ee7a72b871591594958666
[ERROR] WebSocket is not open: readyState 0 (CONNECTING), Stack: Error: WebSocket is not open: readyState 0 (CONNECTING)
	at WebSocket.send (/Users/kevinjohnson/.vscode-insiders/extensions/nicollasr.vscode-streamdeck-4.1.5/node_modules/ws/lib/websocket.js:328:13)
	at ExtensionHub.send (/Users/kevinjohnson/.vscode-insiders/extensions/nicollasr.vscode-streamdeck-4.1.5/out/extensionHub.js:32:25)
	at ExtensionController.changeActiveSession (/Users/kevinjohnson/.vscode-insiders/extensions/nicollasr.vscode-streamdeck-4.1.5/out/extensionController.js:77:18)
	at /Users/kevinjohnson/.vscode-insiders/extensions/nicollasr.vscode-streamdeck-4.1.5/out/extension.js:53:33
	at e._executeContributedCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:639:863)
	at e.$executeContributedCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:640:217)
	at e._doInvokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:804:1013)
	at e._invokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:804:705)
	at e._receiveRequest (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:803:344)
	at e._receiveOneMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:802:156)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:800:416
	at e.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
	at v.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:239:274)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:975:649
	at e.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
	at v.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:239:274)
	at t.PersistentProtocol._receiveMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:243:629)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:240:824
	at e.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
	at p.acceptChunk (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:236:737)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:236:89
	at Socket.t (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:245:185)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
[6/8/2020, 1:46:01 AM] Activation requested to e5564f1a-003f-41bf-be74-0b4ee7a72b871591594958666
[ERROR] WebSocket is not open: readyState 0 (CONNECTING), Stack: Error: WebSocket is not open: readyState 0 (CONNECTING)
	at WebSocket.send (/Users/kevinjohnson/.vscode-insiders/extensions/nicollasr.vscode-streamdeck-4.1.5/node_modules/ws/lib/websocket.js:328:13)
	at ExtensionHub.send (/Users/kevinjohnson/.vscode-insiders/extensions/nicollasr.vscode-streamdeck-4.1.5/out/extensionHub.js:32:25)
	at ExtensionController.changeActiveSession (/Users/kevinjohnson/.vscode-insiders/extensions/nicollasr.vscode-streamdeck-4.1.5/out/extensionController.js:77:18)
	at /Users/kevinjohnson/.vscode-insiders/extensions/nicollasr.vscode-streamdeck-4.1.5/out/extension.js:53:33
	at e._executeContributedCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:639:863)
	at e.$executeContributedCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:640:217)
	at e._doInvokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:804:1013)
	at e._invokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:804:705)
	at e._receiveRequest (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:803:344)
	at e._receiveOneMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:802:156)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:800:416
	at e.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
	at v.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:239:274)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:975:649
	at e.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
	at v.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:239:274)
	at t.PersistentProtocol._receiveMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:243:629)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:240:824
	at e.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
	at p.acceptChunk (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:236:737)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:236:89
	at Socket.t (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:245:185)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
[6/8/2020, 1:46:01 AM] Activation requested to e5564f1a-003f-41bf-be74-0b4ee7a72b871591594958666
[ERROR] WebSocket is not open: readyState 0 (CONNECTING), Stack: Error: WebSocket is not open: readyState 0 (CONNECTING)
	at WebSocket.send (/Users/kevinjohnson/.vscode-insiders/extensions/nicollasr.vscode-streamdeck-4.1.5/node_modules/ws/lib/websocket.js:328:13)
	at ExtensionHub.send (/Users/kevinjohnson/.vscode-insiders/extensions/nicollasr.vscode-streamdeck-4.1.5/out/extensionHub.js:32:25)
	at ExtensionController.changeActiveSession (/Users/kevinjohnson/.vscode-insiders/extensions/nicollasr.vscode-streamdeck-4.1.5/out/extensionController.js:77:18)
	at /Users/kevinjohnson/.vscode-insiders/extensions/nicollasr.vscode-streamdeck-4.1.5/out/extension.js:53:33
	at e._executeContributedCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:639:863)
	at e.$executeContributedCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:640:217)
	at e._doInvokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:804:1013)
	at e._invokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:804:705)
	at e._receiveRequest (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:803:344)
	at e._receiveOneMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:802:156)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:800:416
	at e.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
	at v.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:239:274)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:975:649
	at e.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
	at v.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:239:274)
	at t.PersistentProtocol._receiveMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:243:629)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:240:824
	at e.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
	at p.acceptChunk (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:236:737)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:236:89
	at Socket.t (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:245:185)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
[6/8/2020, 1:46:01 AM] Activation requested to e5564f1a-003f-41bf-be74-0b4ee7a72b871591594958666
[ERROR] WebSocket is not open: readyState 0 (CONNECTING), Stack: Error: WebSocket is not open: readyState 0 (CONNECTING)
	at WebSocket.send (/Users/kevinjohnson/.vscode-insiders/extensions/nicollasr.vscode-streamdeck-4.1.5/node_modules/ws/lib/websocket.js:328:13)
	at ExtensionHub.send (/Users/kevinjohnson/.vscode-insiders/extensions/nicollasr.vscode-streamdeck-4.1.5/out/extensionHub.js:32:25)
	at ExtensionController.changeActiveSession (/Users/kevinjohnson/.vscode-insiders/extensions/nicollasr.vscode-streamdeck-4.1.5/out/extensionController.js:77:18)
	at /Users/kevinjohnson/.vscode-insiders/extensions/nicollasr.vscode-streamdeck-4.1.5/out/extension.js:53:33
	at e._executeContributedCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:639:863)
	at e.$executeContributedCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:640:217)
	at e._doInvokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:804:1013)
	at e._invokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:804:705)
	at e._receiveRequest (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:803:344)
	at e._receiveOneMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:802:156)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:800:416
	at e.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
	at v.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:239:274)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:975:649
	at e.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
	at v.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:239:274)
	at t.PersistentProtocol._receiveMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:243:629)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:240:824
	at e.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
	at p.acceptChunk (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:236:737)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:236:89
	at Socket.t (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:245:185)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
[6/8/2020, 1:46:01 AM] Disconnected from Stream Deck.
[6/8/2020, 1:46:01 AM] Connecting to Stream Deck
```

**Comment by Ajwah** [comment]
I figured that considering that when Elgato Stream Deck automatically updates the VSCode extension; the `settings.ini` file is missing and needs to be recreated on `macos` that the websocket server accordingly is not starting up with the correct host/port settings. As such, I restarted `Stream Deck` app and then I see the following in the Debug Output:

```
[6/8/2020, 2:05:58 AM] Message received, ActiveSessionChangedMessage.: {"id":"ActiveSessionChangedMessage","data":"{\"sessionId\":\"e5564f1a-003f-41bf-be74-0b4ee7a72b871591594958666\"}"}
```

<img width="709" alt="Screen Shot 2020-06-08 at 2 06 11 AM" src="https://user-images.githubusercontent.com/11848116/83997554-a2034580-a92c-11ea-9c90-9e80845098a4.png">

However, when I press a button, it reverts back to the dysfunctional state I am complaining about in this issue :)

Concerning the matter that on `macos` the `settings.ini` file is missing, I would guess that is on account of the directory to be incorrect:
> ~/Library/Application Support/com.elgato.StreamDeck/Plugins/com.nicollasr.streamdeckvsc.mac.sdPlugin/settings.ini

There is no space between the words `ApplicationSupport`, thus the correct directory is rather:
`~/Library/ApplicationSupport/com.elgato.StreamDeck/Plugins/com.nicollasr.streamdeckvsc.mac.sdPlugin`

I assume that this is something that you most likely copy pasted from [the official website](https://developer.elgato.com/documentation/stream-deck/sdk/create-your-own-plugin/). 
Is it possible that you have hardcoded the directory accordingly in the VSCode Plugin and thus it is trying to write the `settings.ini` file to a non existing directory?

**Comment by nicollasricas** [comment]
> I figured that considering that when Elgato Stream Deck automatically updates the VSCode extension; the `settings.ini` file is missing and needs to be recreated on `macos` that the websocket server accordingly is not starting up with the correct host/port settings. As such, I restarted `Stream Deck` app and then I see the following in the Debug Output:

I notice this today when testing a connection with WSL in Linux. Elgato update process deletes the whole folder before extracting the files from the .streamdeckPlugin file which is just a zip file.

In a case where the host or port was changed, the update process will mess with the settings.

However, in your case, It should use the default settings even when the file doesn't exist.

Could you rename the settings.ini, restart the Stream Deck Software and send me the pluginlog.log?

There's a line on this file that shows the location from the message server.

`2020-06-08 07:46:57.1764|INFO|BarRaider.SdTools.Logger|Starting server ws://127.0.0.1:48969`

**Comment by Ajwah** [comment]
I renamed the file, restarted the Elgato service and in VSCode it shows `Deck | Connected | Active`. I proceed to press a button on the device and it changes to: `Deck | Connecting` indicating it disconnected.
This is the contents of the log file as you requested:
```
2020-06-08 20:20:15.5790|DEBUG|BarRaider.SdTools.Logger|Logger Initialized
2020-06-08 20:20:15.6298|INFO|BarRaider.SdTools.Logger|Starting server ws://127.0.0.1:48969
2020-06-08 20:20:15.6761|INFO|BarRaider.SdTools.Logger|Plugin Loading - 6 Actions Found
2020-06-08 20:20:16.0387|INFO|BarRaider.SdTools.Logger|Plugin version: 5.1.2
2020-06-08 20:20:16.0387|INFO|BarRaider.SdTools.Logger|Connecting to Stream Deck
2020-06-08 20:20:16.0726|INFO|BarRaider.SdTools.Logger|Connected to Stream Deck
2020-06-08 20:20:16.0731|INFO|BarRaider.SdTools.Logger|GlobalSettingsManager initialized
2020-06-08 20:20:31.8350|INFO|BarRaider.SdTools.Logger|{"id":"ChangeActiveSessionMessage","data":"{\"sessionId\":\"e5564f1a-003f-41bf-be74-0b4ee7a72b871591594958666\"}"}
2020-06-08 20:20:31.9424|INFO|BarRaider.SdTools.Logger|{"id":"ChangeActiveSessionMessage","data":"{\"sessionId\":\"e5564f1a-003f-41bf-be74-0b4ee7a72b871591594958666\"}"}
2020-06-08 20:20:36.5423|INFO|BarRaider.SdTools.Logger|{"id":"ChangeActiveSessionMessage","data":"{\"sessionId\":\"e5564f1a-003f-41bf-be74-0b4ee7a72b871591594958666\"}"}
2020-06-08 20:20:51.8407|INFO|BarRaider.SdTools.Logger|{"id":"ChangeActiveSessionMessage","data":"{\"sessionId\":\"e5564f1a-003f-41bf-be74-0b4ee7a72b871591594958666\"}"}
2020-06-08 20:20:53.0670|INFO|BarRaider.SdTools.Logger|Disconnect event received
2020-06-08 20:20:53.0676|INFO|BarRaider.SdTools.Logger|Plugin Disconnected - Exiting
```

**Comment by nicollasricas** [comment]
Please try with this update and let me know if it's working.

I noticed that you are using an insider version, could you send the info showed at Help->About in VS Code?

![image](https://user-images.githubusercontent.com/7860985/84099053-ba2f9f00-a9d6-11ea-8ac7-ea0e8f82ed98.png)

[vscode-streamdeck-4.1.5.zip](https://github.com/nicollasricas/vscode-streamdeck/files/4749578/vscode-streamdeck-4.1.5.zip)

**Comment by Ajwah** [comment]
Will try out the `vix` install
<img width="418" alt="Screen Shot 2020-06-08 at 10 43 07 PM" src="https://user-images.githubusercontent.com/11848116/84100231-6d00fc80-a9d9-11ea-9bc3-3cbbb6512d4a.png">

**Comment by nicollasricas** [comment]
> `ECONNREFUSED` would indicate to me it is trying to start a websocket server on a port that is already assigned. I am kinda puzzled how it would be possible for this to occur when I have restarted both VSCode as well as Stream Deck. Is it possible that multiple windows are trying to start up the server at the same time?

The only way I can imagine that this would happen is if when you close the stream deck, it doesn't kill the plugin process leaving opened connection.

Could you try to change the port? I will install the insider version tomorrow in my VM and run the test script.

Although the connection from the client (vs code) to the server (stream deck) wasn't possible, the plugin started with no errors.

Try to update the plugin on stream deck. I forced some initialization logs from the plugin host.

https://1drv.ms/u/s!Agq8DfGl4Hpxil_I8Bxbk_dbCUpY

**Comment by Ajwah** [comment]
I tried changing the port and I tried the custom plugin for Stream Deck you shared in the last comment to no avail. The behaviour as reported above remains in both cases.

**Comment by nicollasricas** [comment]
Which stream deck action are you trying? Execute command? Terminal command?

**Comment by Ajwah** [comment]
> Which stream deck action are you trying? Execute command? Terminal command?

None of them.
I have a dedicated folder for VSCode in which resides all the various actions that I use.
Merely pressing that folder button makes it crash. I am not even able to use any specific action

**Comment by nicollasricas** [comment]
Try adding a new terminal command action with any text as command outside that folder in Stream Deck home page and press it.

**Comment by Ajwah** [comment]
> Try adding a new terminal command action with any text as command outside that folder in Stream Deck home page and press it.

I tried doing so but consistent with the above the server crashes when that button is loaded. I do not even have the chance to press it.
I also tried to localize the problem to a specific action; to see if it is only one specific command that trips up the server or if it is all of them. After three different actions(Execute Terminal Command, Execute Command and Open Folder) crashing the server I conclude that the problem extends to all of them.

**Comment by nicollasricas** [comment]
To create this plugin I've been using the streamdeck-tools which handle all communication between stream deck, property inspector and the plugin.

There are two web servers one from the Stream Deck and one from my plugin. The plugin message server does nothing until you press an action, so if it is crashing when you open the folder it should be a communication problem between the Stream Deck and the "streamdeck-tools" or in the property inspector.

In the last update, I updated the dependencies to create a new feature that I'm working on, your issue came after that.

Try with this version:
https://1drv.ms/u/s!Agq8DfGl4Hpxii0E1vCnAMBvjERG

If still not working follow this procedure to enable debugging.
https://developer.elgato.com/documentation/stream-deck/sdk/create-your-own-plugin/#debugging

After you run the terminal command and open the debug URL you should see a list of inspectable pages, inspect them before opening the folder.

Thank you for helping out with this issue as I mentioned before I do have a coverage script running on Windows and Linux, but my macOS VM doesn't boot anymore and since I don't own one your help is very appreciated.

**Comment by Ajwah** [comment]
> Thank you for helping out with this issue as I mentioned before I do have a coverage script running on Windows and Linux, but my macOS VM doesn't boot anymore and since I don't own one your help is very appreciated.

I would not mind testing new releases on my local before you push them out.

**Comment by nicollasricas** [comment]
Whenever you have time could you enable the debugging and inspect the pages? I will report the error to the BarRaider author of the https://github.com/BarRaider/streamdeck-tools.

**Comment by Ajwah** [comment]
> Whenever you have time could you enable the debugging and inspect the pages? I will report the error to the BarRaider author of the https://github.com/BarRaider/streamdeck-tools.

I will try to do soon.

**Comment by paulhennell** [comment]
I'm also seeing this same 'connecting error' in vscode on mac osx. Built a workaround by changing to the hotkey action and shortcuts for the time being which works ok for key needs (mostly running tests!)

If I can help with additional debug logs or anything let me know (I'm not super strong on VScode stuff, but happy to assist if I can!)

**Comment by nicollasricas** [comment]
Update sent to Elgato wait or download manually [here](https://github.com/nicollasricas/streamdeckvsc/releases/latest).
